### ISSUE TITLE
http的网址检测报错

### ISSUE THREAD

**Issue by shen771** [rabbitmask/Libra#11]
PS D:\Libra-main> python Libra.py -u http://www.xxxx.net/

██╗     ██╗██████╗ ██████╗  █████╗
██║     ██║██╔══██╗██╔══██╗██╔══██╗
██║     ██║██████╔╝██████╔╝███████║
██║     ██║██╔══██╗██╔══██╗██╔══██║
███████╗██║██████╔╝██║  ██║██║  ██║
╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

          Libra | 网站篡改、暗链、死链监测平台
          By RabbitMask | V 1.1

Traceback (most recent call last):
  File "D:\Libra-main\Libra.py", line 19, in <module>
    Console()
  File "D:\Libra-main\Framework\Console.py", line 33, in Console
    res=getweb.run(args.url)
  File "D:\Libra-main\Moudle\Crawler\getweb.py", line 123, in run
    res = poolmana(url)
  File "D:\Libra-main\Moudle\Crawler\getweb.py", line 112, in poolmana
    urls = crawler_api(url)
  File "D:\Libra-main\Moudle\Crawler\getweb.py", line 49, in crawler_api
    if i[0]=='/':
IndexError: string index out of range
PS D:\Libra-main>

**Comment by rabbitmask** [comment]
感谢关注，Libra项目意外收获了近300个Star，这份信任让我深感荣幸。同时也为长期积压的Issues未能及时回复而深表歉意。

项目历程回顾

Libra最初诞生于一次应急需求，仅用两天时间快速开发完成的概念验证脚本。由于开发时间紧迫且缺乏充分的架构设计，代码结构和思路确实存在许多不足之处。

随着项目在实际业务中的应用，我们基于大量实战经验对检测引擎进行了深度优化，包括：

针对黑帽SEO常用编码技术的专项识别
集成主流加解密算法的检测能力
经慎重考虑，现决定将商业版本中的部分核心改进回馈给开源版本。新版本在检测精度、性能表现和代码质量方面都有显著提升，相较于早期的纯正则匹配方案有了质的飞跃。

希望全新的Libra能够为有需求的师傅们提供些许帮助。
