### ISSUE TITLE
运行不了哇哥

### ISSUE THREAD

**Issue by xiaotianccc** [rabbitmask/Libra#2]
─# python3 Libra.py -h                                                  1 ⨯
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usrb/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usrb/python3.9tp/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usrb/python3.9tp/client.py", line 950, in send
    self.connect()
  File "/usrb/python3.9tp/client.py", line 1417, in connect
    super().connect()
  File "/usrb/python3.9tp/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usrb/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usrb/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/usrb/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usrb/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usrb/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usrb/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usrb/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usrb/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
Traceback (most recent call last):
  File "/usrb/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usrb/python3.9tp/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usrb/python3.9tp/client.py", line 950, in send
    self.connect()
  File "/usrb/python3.9tp/client.py", line 1417, in connect
    super().connect()
  File "/usrb/python3.9tp/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usrb/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usrb/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/usrb/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usrb/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usrb/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usrb/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usrb/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usrb/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usrb/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usrb/python3.9tp/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usrb/python3.9tp/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usrb/python3.9tp/client.py", line 950, in send
    self.connect()
  File "/usrb/python3.9tp/client.py", line 1417, in connect
    super().connect()
  File "/usrb/python3.9tp/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usrb/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usrb/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/usrb/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usrb/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usrb/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usrb/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usrb/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usrb/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homeli/Desktop/Libra-main/Libra.py", line 12, in <module>
    from Framework.Console import Console
  File "/homeli/Desktop/Libra-main/Framework/Console.py", line 15, in <module>
    from Moudle.Crawler import getweb
  File "/homeli/Desktop/Libra-main/Moudle/Crawler/getweb.py", line 15, in <module>
    from Config.config_requests import headers
  File "/homeli/Desktop/Libra-main/Config/config_requests.py", line 23, in <module>
    ua = UserAgent()
  File "/usr/localb/python3.9/dist-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/usr/localb/python3.9/dist-packages/fake_useragent/fake.py", line 75, in load
    self.data = load_cached(
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 187, in load
    ret = json.loads(get(
  File "/usr/localb/python3.9/dist-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by rabbitmask** [comment]
其实是fake_useragent这个库的问题，他在加载时会同步ua头库，如果你网不好就会报错，我暂时换下来了，你可以手动替换config_requests.py文件或者重新拉取一遍～
